import express from 'express';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import User from '../models/User.js';
import transporter from '../mailer.js';

const router = express.Router();

// ==========================================
// 🛡️ AUTH MIDDLEWARE
// ==========================================
function authMiddleware(req, res, next) {
  const token = req.header("Authorization")?.replace("Bearer ", "");
  if (!token) return res.status(401).json({ error: "No token, authorization denied" });

  try {
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    req.user = decoded;
    next();
  } catch (err) {
    res.status(401).json({ error: "Token is not valid or has expired" });
  }
}

// ==========================================
// 📑 REGISTER
// ==========================================
router.post("/register", async (req, res) => {
  try {
    const { name, email, password, phone, city, style, level } = req.body;

    if (!name || !email) {
      return res.status(400).json({ error: "Name and Email are required fields" });
    }

    let existingUser = await User.findOne({ email });
    if (existingUser) return res.status(400).json({ error: "User already exists" });

    let passwordToHash = password;
    let isAutoGenerated = false;

    if (!passwordToHash || passwordToHash.trim() === "") {
      passwordToHash = crypto.randomBytes(5).toString("hex");
      isAutoGenerated = true;
    }

    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(passwordToHash, salt);

    const newUser = new User({
      name: name.trim(),
      email: email.toLowerCase().trim(),
      password: hashedPassword,
      phone: phone || "",
      city: city || "",
      style: style || "",
      level: level || ""
    });

    await newUser.save();

    let emailText = `Hello ${name},\n\nWelcome to Pragya Yoga! Your registration was successful.\n\n`;

    if (isAutoGenerated) {
      emailText += `An administrator has created your profile. Here are your temporary login credentials:\n`;
      emailText += `Email: ${email}\n`;
      emailText += `Temporary Password: ${passwordToHash}\n\n`;
      emailText += `Please log in and update your password from your dashboard profile section immediately.`;
    } else {
      emailText += `You can now log in using the secure password you selected during registration.\n\n`;
      emailText += `If you ever need to change your password, you can do so from your student dashboard.`;
    }

    try {
      await transporter.sendMail({
        from: process.env.EMAIL_USER,
        to: email,
        subject: isAutoGenerated ? "Your Pragya Yoga Account Credentials" : "Welcome to Pragya Yoga!",
        text: emailText
      });
    } catch (mailErr) {
      console.error("Mailer failed, but user was created successfully:", mailErr);
    }

    res.json({
      msg: isAutoGenerated
        ? "Student profile created successfully. Temporary credentials emailed."
        : "User registered successfully.",
      autoGenerated: isAutoGenerated
    });
  } catch (err) {
    console.error("Register error:", err);
    res.status(500).json({ error: "Server error" });
  }
});

// ==========================================
// 🔐 LOGIN — returns role so frontend can route correctly
// ==========================================
router.post("/login", async (req, res) => {
  try {
    const { email, password } = req.body;
    const user = await User.findOne({ email: email.toLowerCase().trim() });
    if (!user) return res.status(400).json({ error: "Invalid credentials" });

    const isMatch = await bcrypt.compare(password, user.password);
    if (!isMatch) return res.status(400).json({ error: "Invalid credentials" });

    const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET, { expiresIn: "7d" });

    res.json({
      msg: "Login successful",
      token,
      user: {
        id:    user._id,
        name:  user.name,
        email: user.email,
        role:  user.role,          // ← THE FIX
        phone: user.phone || "",
        city:  user.city  || "",
        style: user.style || "",
        level: user.level || "",
        planMonths:    user.planMonths    || 0,
        referralCount: user.referralCount || 0,
        months:        user.months        || 0,
        certifs:       user.certifs       || 0,
        stats:    user.stats    || { classes: 0, attendancePct: 0 },
        progress: user.progress || { flexibility: 0, strength: 0, breathing: 0, meditation: 0 },
        badges:   user.badges   || [],
      }
    });
  } catch (err) {
    console.error("Login error:", err);
    res.status(500).json({ error: "Server error" });
  }
});

// ==========================================
// 🔑 FORGOT PASSWORD
// ==========================================
router.post("/forgot-password", async (req, res) => {
  try {
    const { email } = req.body;
    const user = await User.findOne({ email });
    if (!user) return res.status(400).json({ error: "User not found" });

    const token = jwt.sign({ id: user._id }, process.env.JWT_SECRET, { expiresIn: "15m" });
    const resetLink = `http://localhost:5173/reset-password/${token}`;

    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: email,
      subject: "Password Reset Request",
      text: `Reset link: ${resetLink}`
    });

    res.json({ msg: "Reset link sent." });
  } catch (err) {
    console.error("Forgot password error:", err);
    res.status(500).json({ error: "Server error" });
  }
});

// ==========================================
// 👤 GET PROFILE
// ==========================================
router.get("/profile", authMiddleware, async (req, res) => {
  try {
    const user = await User.findById(req.user.id).select("-password");
    if (!user) return res.status(404).json({ error: "User not found" });
    res.json(user);
  } catch (err) {
    console.error("Get profile error:", err);
    res.status(500).json({ error: "Server error" });
  }
});

// ==========================================
// ✏️ UPDATE PROFILE
// ==========================================
router.put("/profile", authMiddleware, async (req, res) => {
  try {
    const { name, email, phone, city, style, level, newPassword } = req.body;

    const updatedFields = {};
    if (name  !== undefined) updatedFields.name  = name;
    if (phone !== undefined) updatedFields.phone = phone;
    if (city  !== undefined) updatedFields.city  = city;
    if (style !== undefined) updatedFields.style = style;
    if (level !== undefined) updatedFields.level = level;

    if (newPassword && newPassword.trim() !== "") {
      const salt = await bcrypt.genSalt(10);
      updatedFields.password = await bcrypt.hash(newPassword, salt);
    }

    if (email !== undefined) {
      const emailOwner = await User.findOne({ email });
      if (emailOwner && emailOwner._id.toString() !== req.user.id) {
        return res.status(400).json({ error: "Email is already in use by another account" });
      }
      updatedFields.email = email;
    }

    const updatedUser = await User.findByIdAndUpdate(
      req.user.id,
      { $set: updatedFields },
      { new: true, runValidators: true }
    ).select("-password");

    if (!updatedUser) return res.status(404).json({ error: "User not found" });

    res.json(updatedUser);
  } catch (err) {
    console.error("Profile update error:", err);
    res.status(500).json({ error: "Could not update profile" });
  }
});

export { authMiddleware };
export default router;
