// ============================================================
// controllers/authController.js
// Registration, login, token refresh, logout, password reset,
// profile read/update, change password.
// ============================================================
import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import User from '../models/User.js';
import transporter from '../mailer.js';
import asyncHandler from '../utils/asyncHandler.js';
import ApiError from '../utils/ApiError.js';
import {
  signAccessToken,
  signRefreshToken,
  verifyRefreshToken,
  signPurposeToken,
  verifyPurposeToken,
} from '../utils/token.js';
import { ensureReferral, applyReferral } from '../services/referralService.js';
import { buildStudentDashboard } from '../services/dashboardService.js';

const FRONTEND_URL = process.env.FRONTEND_URL || 'http://localhost:5173';
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

const hashToken = (t) => crypto.createHash('sha256').update(t).digest('hex');

// Shape returned to the client on auth — matches what the React app stores.
function publicUser(user) {
  return {
    id: user._id,
    _id: user._id,
    name: user.name,
    email: user.email,
    role: user.role,
    status: user.status,
    phone: user.phone || '',
    city: user.city || '',
    style: user.style || '',
    level: user.level || '',
    planMonths: user.planMonths || 0,
    planActive: (user.planMonths || 0) > 0,
    referralCount: user.referralCount || 0,
    months: user.months || 0,
    certifs: user.certifs || 0,
    stats: user.stats || { classes: 0, attendancePct: 0 },
    progress: user.progress || { flexibility: 0, strength: 0, breathing: 0, meditation: 0 },
    badges: user.badges || [],
    unreadNotifications: user.unreadNotifications || 0,
  };
}

async function issueTokens(user) {
  const accessToken = signAccessToken(user);
  const refreshToken = signRefreshToken(user);
  // Persist a hash of the refresh token so it can be revoked on logout.
  await User.findByIdAndUpdate(user._id, {
    $push: { refreshTokens: { $each: [hashToken(refreshToken)], $slice: -5 } },
  });
  return { accessToken, refreshToken };
}

// ── POST /api/auth/register ──────────────────────────────────
export const register = asyncHandler(async (req, res) => {
  const { name, email, password, phone, city, style, level, ref } = req.body;

  if (!name || !email) throw ApiError.badRequest('Name and email are required');
  if (!EMAIL_RE.test(email)) throw ApiError.badRequest('Please provide a valid email address');

  const existing = await User.findOne({ email: email.toLowerCase().trim() });
  if (existing) throw ApiError.conflict('An account with this email already exists');

  // Allow admin-created students to omit a password (auto-generated + emailed).
  let raw = password;
  let autoGenerated = false;
  if (!raw || raw.trim() === '') {
    raw = crypto.randomBytes(5).toString('hex');
    autoGenerated = true;
  }
  if (!autoGenerated && raw.length < 6) throw ApiError.badRequest('Password must be at least 6 characters');

  const hashed = await bcrypt.hash(raw, await bcrypt.genSalt(10));

  const user = await User.create({
    name: name.trim(),
    email: email.toLowerCase().trim(),
    password: hashed,
    phone: phone || '',
    city: city || '',
    style: style || 'Hatha',
    level: level || 'Beginner',
  });

  // Every student gets a referral record; apply inbound referral credit.
  await ensureReferral(user);
  if (ref) await applyReferral(ref, user);

  // Welcome / credentials email (best-effort).
  try {
    const text = autoGenerated
      ? `Hello ${name},\n\nAn administrator created your Pragya Yoga account.\nEmail: ${user.email}\nTemporary Password: ${raw}\n\nPlease log in and change your password.`
      : `Hello ${name},\n\nWelcome to Pragya Yoga! Your account is ready — sign in with the password you chose.`;
    await transporter.sendMail({
      from: process.env.EMAIL_USER,
      to: user.email,
      subject: autoGenerated ? 'Your Pragya Yoga Account Credentials' : 'Welcome to Pragya Yoga!',
      text,
    });
  } catch (err) {
    console.error('Welcome email failed (user still created):', err.message);
  }

  res.status(201).json({
    success: true,
    msg: autoGenerated ? 'Student profile created. Temporary credentials emailed.' : 'Registration successful',
    autoGenerated,
    user: publicUser(user),
  });
});

// ── POST /api/auth/login ─────────────────────────────────────
export const login = asyncHandler(async (req, res) => {
  const { email, password } = req.body;
  if (!email || !password) throw ApiError.badRequest('Email and password are required');

  const user = await User.findOne({ email: email.toLowerCase().trim() });
  if (!user) throw ApiError.unauthorized('Invalid credentials');
  if (user.status === 'banned') throw ApiError.forbidden('Your account has been suspended');

  const match = await bcrypt.compare(password, user.password);
  if (!match) throw ApiError.unauthorized('Invalid credentials');

  user.lastLogin = new Date();
  await user.save();

  const { accessToken, refreshToken } = await issueTokens(user);

  res.json({
    success: true,
    msg: 'Login successful',
    token: accessToken,
    refreshToken,
    user: publicUser(user),
  });
});

// ── POST /api/auth/refresh ───────────────────────────────────
export const refresh = asyncHandler(async (req, res) => {
  const { refreshToken } = req.body;
  if (!refreshToken) throw ApiError.unauthorized('Refresh token required');

  let decoded;
  try {
    decoded = verifyRefreshToken(refreshToken);
  } catch {
    throw ApiError.unauthorized('Invalid or expired refresh token');
  }

  const user = await User.findById(decoded.id).select('+refreshTokens');
  if (!user || !user.refreshTokens.includes(hashToken(refreshToken))) {
    throw ApiError.unauthorized('Refresh token has been revoked');
  }

  const accessToken = signAccessToken(user);
  res.json({ success: true, token: accessToken });
});

// ── POST /api/auth/logout ────────────────────────────────────
export const logout = asyncHandler(async (req, res) => {
  const { refreshToken } = req.body;
  if (refreshToken) {
    try {
      const decoded = verifyRefreshToken(refreshToken);
      await User.findByIdAndUpdate(decoded.id, { $pull: { refreshTokens: hashToken(refreshToken) } });
    } catch {
      /* token already invalid — nothing to revoke */
    }
  }
  res.json({ success: true, msg: 'Logged out' });
});

// ── POST /api/auth/forgot-password ───────────────────────────
export const forgotPassword = asyncHandler(async (req, res) => {
  const { email } = req.body;
  if (!email) throw ApiError.badRequest('Email is required');

  const user = await User.findOne({ email: email.toLowerCase().trim() });
  // Always return success to avoid leaking which emails are registered.
  if (user) {
    const token = signPurposeToken({ id: user._id, purpose: 'reset' }, '15m');
    user.resetTokenHash = hashToken(token);
    user.resetTokenExpires = new Date(Date.now() + 15 * 60 * 1000);
    await user.save();

    const resetLink = `${FRONTEND_URL}/reset-password/${token}`;
    try {
      await transporter.sendMail({
        from: process.env.EMAIL_USER,
        to: user.email,
        subject: 'Reset your Pragya Yoga password',
        text: `You requested a password reset.\n\nReset link (valid 15 minutes):\n${resetLink}\n\nIf you didn't request this, ignore this email.`,
      });
    } catch (err) {
      console.error('Reset email failed:', err.message);
    }
  }

  res.json({ success: true, msg: 'If that email is registered, a reset link has been sent.' });
});

// ── POST /api/auth/reset-password/:token ─────────────────────
export const resetPassword = asyncHandler(async (req, res) => {
  const { token } = req.params;
  const { newPassword } = req.body;
  if (!newPassword || newPassword.length < 6) throw ApiError.badRequest('Password must be at least 6 characters');

  let decoded;
  try {
    decoded = verifyPurposeToken(token);
  } catch {
    throw ApiError.badRequest('Reset link is invalid or has expired');
  }
  if (decoded.purpose !== 'reset') throw ApiError.badRequest('Invalid reset token');

  const user = await User.findById(decoded.id).select('+resetTokenHash +resetTokenExpires');
  if (!user || user.resetTokenHash !== hashToken(token) || !user.resetTokenExpires || user.resetTokenExpires < new Date()) {
    throw ApiError.badRequest('Reset link is invalid or has expired');
  }

  user.password = await bcrypt.hash(newPassword, await bcrypt.genSalt(10));
  user.resetTokenHash = null;
  user.resetTokenExpires = null;
  user.refreshTokens = []; // force re-login everywhere
  await user.save();

  res.json({ success: true, msg: 'Password reset successful. You can now sign in.' });
});

// ── GET /api/auth/profile ────────────────────────────────────
// Students receive the fully-aggregated dashboard object; admins
// receive their user record.
export const getProfile = asyncHandler(async (req, res) => {
  if (req.user.role === 'admin') {
    return res.json(publicUser(req.user));
  }
  const dashboard = await buildStudentDashboard(req.user._id);
  if (!dashboard) throw ApiError.notFound('Profile not found');
  res.json(dashboard);
});

// ── PUT /api/auth/profile ────────────────────────────────────
export const updateProfile = asyncHandler(async (req, res) => {
  const { name, phone, city, style, level, bio, newPassword } = req.body;
  const updates = {};
  if (name !== undefined) updates.name = name.trim();
  if (phone !== undefined) updates.phone = phone;
  if (city !== undefined) updates.city = city;
  if (style !== undefined) updates.style = style;
  if (level !== undefined) updates.level = level;
  if (bio !== undefined) updates.bio = bio;
  // NB: email is intentionally immutable from the profile screen.

  if (newPassword && newPassword.trim() !== '') {
    if (newPassword.length < 6) throw ApiError.badRequest('Password must be at least 6 characters');
    updates.password = await bcrypt.hash(newPassword, await bcrypt.genSalt(10));
  }

  await User.findByIdAndUpdate(req.user._id, { $set: updates }, { runValidators: true });

  // Return the refreshed aggregated dashboard so the UI stays in sync.
  const dashboard = await buildStudentDashboard(req.user._id);
  res.json(dashboard);
});

// ── POST /api/auth/change-password ───────────────────────────
export const changePassword = asyncHandler(async (req, res) => {
  const { currentPassword, newPassword } = req.body;
  if (!currentPassword || !newPassword) throw ApiError.badRequest('Both current and new password are required');
  if (newPassword.length < 6) throw ApiError.badRequest('New password must be at least 6 characters');

  const user = await User.findById(req.user._id);
  const match = await bcrypt.compare(currentPassword, user.password);
  if (!match) throw ApiError.badRequest('Current password is incorrect');

  user.password = await bcrypt.hash(newPassword, await bcrypt.genSalt(10));
  await user.save();
  res.json({ success: true, msg: 'Password changed successfully' });
});
